<?php
$API_KEY = "YukCSlQ06ZSWR609CogxpusvXZJQUFNWVEdSTlROWEhBU0g0";
$SECRECT_KEY="YtzKRaPR8AokZry0rEcsuZ8frkIKqEtjQaXqmJMit29QUFNWVEdSTlROWEhBU0g0";
$USERNAME="NPrashant";
$PASSWORD="Password123#";
?>